#:schema node_modules/wrangler/config-schema.json
name = "my-svelte-app"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"
assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

vars = { MY_VARIABLE = "from local wrangler.toml" }

kv_namespaces = [
    { binding = "YOUR_KV_NAMESPACE", id = "0e0cee0606dd4334aeddbe0fd0a27011" }
]

[env.production]

vars = { MY_VARIABLE = "from wrangler.toml" }

kv_namespaces = [
    { binding = "YOUR_KV_NAMESPACE", id = "0e0cee0606dd4334aeddbe0fd0a27011" }
]

